/* ============================================================
   The Seasonal Refresh — quarterly digest (deterministic, no tokens)
   ------------------------------------------------------------
   Runs under Node (quarterly cron or `npm run season`). It loads the
   REAL data.js + memory-graph.js + season.js, asks CASON_SEASON for
   this season's rotation (featured persona, a documented fact to
   remember, the open line being chased, where to dig), re-attests the
   record's integrity stamp, and writes a short seasonal digest to
   research/proposals/ for a human to review.

   It spends NO tokens — it only summarizes the deterministic rotation
   that the live page already shows. Propose, not publish: merging the
   PR keeps the seasonal note in the record; closing it discards it.

   Flags:  --out <dir>  proposals dir (default research/proposals)
           --date <iso> override the date (testing); default = now
   ============================================================ */
'use strict';
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const LIVING = path.join(ROOT, 'ui_kits', 'living-line');
const args = process.argv.slice(2);
function flag(name, def) { const i = args.indexOf('--' + name); return i !== -1 ? (args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : true) : def; }
const OUT = path.join(ROOT, String(flag('out', 'research/proposals')));
const DATE = flag('date', null) ? new Date(String(flag('date', null))) : new Date();

function load() {
  const ctx = { console: console, localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} } };
  ctx.window = ctx; vm.createContext(ctx);
  [path.join(LIVING, '..', 'family-tree-app', 'data.js'), path.join(LIVING, 'memory-graph.js'), path.join(LIVING, 'personas.js'), path.join(LIVING, 'season.js')]
    .forEach(function (f) { vm.runInContext(fs.readFileSync(f, 'utf8'), ctx, { filename: f }); });
  return ctx.CASON_SEASON;
}

function clip(s, n) { s = String(s || '').replace(/\s+/g, ' ').trim(); return s.length > n ? s.slice(0, n) + '…' : s; }

(function main() {
  const SEASON = load();
  if (!SEASON) { console.error('season.js did not load'); process.exit(1); }
  const s = SEASON.current(DATE);
  const iso = DATE.toISOString().slice(0, 10);

  let md = '# Seasonal refresh — ' + s.label + ' ' + DATE.getFullYear() + ' (' + iso + ')\n\n';
  md += '> ' + s.emoji + ' *' + s.theme + '*\n\n';
  md += 'Deterministic seasonal rotation — the same content the homestead shows this season, captured for the record. ';
  md += 'Nothing here is a new claim; it re-features what is already documented. **Propose, not publish** — merge to keep this note, close to discard.\n\n';
  md += '**Integrity attestation:** `' + s.attest + '` — ' + s.stats.people + ' people · ' + s.stats.sources + ' sources · ' + s.stats.openLines + ' open lines.\n\n---\n\n';
  if (s.featured) md += '### Featured this season\n**' + s.featured.name + '**' + (s.featured.line ? ' — ' + s.featured.line : '') + '\n\n';
  if (s.highlight) md += '### A record to remember' + (s.highlight.owner ? ' — ' + s.highlight.owner : '') + '\n> ' + clip(s.highlight.text, 400) + '\n\n';
  if (s.question) md += '### The line is chasing\n**' + s.question.name + '** — ' + clip(s.question.text, 300) + '\n\n_(The Keeper can research this open line on its next pass.)_\n\n';
  md += '### Where we’re digging this season\n' + s.archivalFocus + '\n\n---\n_Generated by the seasonal refresh. It re-features; it never invents._\n';

  fs.mkdirSync(OUT, { recursive: true });
  const file = path.join(OUT, 'season-' + iso + '.md');
  fs.writeFileSync(file, md);
  console.log('Wrote ' + path.relative(ROOT, file) + ' — ' + s.label + ' ' + DATE.getFullYear() + ', attest ' + s.attest + '.');
})();
